[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/search/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio"]